import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

// Writes (or checks) src/index.ts, src/<category>/index.ts and src/types/index.ts.
// Run with --check to verify the files on disk match what this script would write.

const root = join(import.meta.dirname, '..')
const srcDir = join(root, 'src')
const GENERATED_HEADER =
  '// This file is generated by scripts/barrels.ts. Do not edit it by hand.\n'

const isDirectory = (path: string): boolean => {
  try {
    return statSync(path).isDirectory()
  } catch {
    return false
  }
}

const camelToPascal = (name: string): string => name.charAt(0).toUpperCase() + name.slice(1)

const kebabToCamel = (name: string): string =>
  name.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase())

const kebabToPascal = (name: string): string => camelToPascal(kebabToCamel(name))

const listCategories = (): string[] =>
  readdirSync(srcDir)
    .filter((name) => name !== 'types' && isDirectory(join(srcDir, name)))
    .sort()

const listFunctions = (category: string): string[] =>
  readdirSync(join(srcDir, category))
    .filter((name) => isDirectory(join(srcDir, category, name)))
    .sort()

const categoryBarrel = (category: string): string => {
  const lines = listFunctions(category).map((fn) => `export * from './${fn}/${fn}'`)
  return `${GENERATED_HEADER}${lines.join('\n')}${lines.length > 0 ? '\n' : ''}`
}

const rootBarrel = (): string => {
  const lines = listCategories().map((category) => `export * from './${category}'`)
  return `${GENERATED_HEADER}${lines.join('\n')}${lines.length > 0 ? '\n' : ''}`
}

const exportNamePattern = /export\s+(?:type|interface)\s+([A-Za-z0-9_]+)/g

const typesBarrel = (): string => {
  const seen = new Map<string, string>()
  const lines: string[] = []

  for (const category of listCategories()) {
    for (const fn of listFunctions(category)) {
      const typesPath = join(srcDir, category, fn, `${fn}.types.ts`)
      let content: string
      try {
        content = readFileSync(typesPath, 'utf8')
      } catch {
        throw new Error(`Missing types file: ${typesPath}`)
      }

      const expectedPrefix = kebabToPascal(fn)
      for (const match of content.matchAll(exportNamePattern)) {
        const typeName = match[1]
        if (typeName === undefined) {
          continue
        }
        if (!typeName.startsWith(expectedPrefix)) {
          throw new Error(`Type "${typeName}" in ${typesPath} must start with "${expectedPrefix}".`)
        }
        const existing = seen.get(typeName)
        if (existing !== undefined) {
          throw new Error(
            `Type name collision: "${typeName}" is exported from both ${existing} and ${typesPath}.`,
          )
        }
        seen.set(typeName, typesPath)
      }

      lines.push(`export * from '../${category}/${fn}/${fn}.types'`)
    }
  }

  return `${GENERATED_HEADER}${lines.join('\n')}${lines.length > 0 ? '\n' : ''}`
}

const targets = (): Array<{ path: string; content: string }> => [
  { path: join(srcDir, 'index.ts'), content: rootBarrel() },
  ...listCategories().map((category) => ({
    path: join(srcDir, category, 'index.ts'),
    content: categoryBarrel(category),
  })),
  { path: join(srcDir, 'types', 'index.ts'), content: typesBarrel() },
]

const checkMode = process.argv.includes('--check')

let hasError = false
for (const { path, content } of targets()) {
  let current: string | undefined
  try {
    current = readFileSync(path, 'utf8')
  } catch {
    current = undefined
  }

  if (checkMode) {
    if (current !== content) {
      console.error(`Stale or missing barrel: ${path}`)
      hasError = true
    }
    continue
  }

  if (current !== content) {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, content)
    console.log(`Wrote ${path}`)
  }
}

if (checkMode && hasError) {
  console.error('\nBarrels are out of date. Run "npm run barrels" to fix this.')
  process.exit(1)
}
