import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

// Copies root Markdown files into docs/ so the VitePress site and the root file can never
// diverge. The root file is the only one a person edits; this script writes the docs copy.

const root = join(import.meta.dirname, '..')

const sources: ReadonlyArray<{ from: string; to: string }> = [
  { from: 'CONTRIBUTING.md', to: 'docs/contributing.md' },
  { from: 'AI-POLICY.md', to: 'docs/ai-policy.md' },
]

// Root-relative links only make sense on GitHub. Rewrite them to VitePress routes for the copy.
const forDocsSite = (content: string): string =>
  content
    .replace(/\]\(\.\/AI-POLICY\.md\)/g, '](/ai-policy)')
    .replace(/\]\(\.\/docs\/guide\/([\w-]+)\.md\)/g, '](/guide/$1)')

for (const { from, to } of sources) {
  const content = readFileSync(join(root, from), 'utf8')
  const notice = `<!-- Generated from ../${from} by scripts/copy-docs.ts. Do not edit this file directly. -->\n\n`
  writeFileSync(join(root, to), notice + forDocsSite(content))
  console.log(`Wrote ${to}`)
}
